# https://hub.docker.com/r/klerith/k8s-teslo-backend
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # echo -n "cualquier-seed-para-jwt" | base64
  JWT_SECRET: Y3VhbHF1aWVyLXNlZWQtcGFyYS1qd3Q=