apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-admin-deployment
  labels:
    app: pg-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-admin
  template:
    metadata:
      labels:
        app: pg-admin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:6.17
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secrets
              key: PG_PASSWORD
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: pgadmin-secrets
              key: PG_USER_EMAIL
          # da errores si no se pone este ultimo
        - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
          value: "False"

---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  type: NodePort

  selector:
    app: pg-admin
  ports:
  - protocol:  TCP
    port:  8080
    targetPort:  80
    nodePort: 30001
